/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.lemonade.server.api

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.autoconfigure.domain.EntityScan
import org.springframework.boot.runApplication
import org.springframework.data.jpa.repository.config.EnableJpaRepositories

@EntityScan(basePackages = ["com.lemonade.server.domain"])
@EnableJpaRepositories(basePackages = ["com.lemonade.server"])
@SpringBootApplication(scanBasePackages = ["com.lemonade.server"])
class Application

fun main(args: Array<String>) {
    runApplication<Application>(*args)
}
